version: "3"
services:
  frontend:
        image: frontend:v5
        container_name: frontend
        stdin_open: true
        environment:
           NODE_ENV: backend1
        ports:
             - "3000:3000"
        depends_on:
             - backend
  backend:
      image: backend:v5
      container_name: backend1
#      environment:
#         DB_NAME: loizenaidb
#         DB_USERNAME: postgres
#         DB_PASSWORD: 12345
#         DB_HOST: postgres
#          database: loizenaidb
#          username: postgres
#          password: 12345
#          host: postgres
      ports:
          - "8080:8080"
      depends_on:
            - postgres
  postgres:
          image: postgres:latest
          container_name: postgres
          ports:
              - "5432:5432"
          environment:
            POSTGRES_PASSWORD: 12345
            POSTGRES_USER: postgres
            POSTGRES_DB: loizenaidb


