version: "3"
services:
  postgres:
      image: postgres:latest
      container_name: postgres
      ports:
          - "5432:5432"
      environment:
        POSTGRES_PASSWORD: 123
        POSTGRES_DB: loizenaidb
        POSTGRES_USER: postgres
  backend:
    image: backend:v6
    container_name: backend
    environment:
      database: loizenaidb
      username: postgres
      password: 123
      host: postgres
    ports:
        - "8080:8080"
  frontend:
      image: naveen5035/frontend:latest
      container_name: frontend
      stdin_open: true
      ports:
            - "3000:3000"