version: "3"
services:
  frontend:
        image: naveen5035/frontend:v2
        container_name: frontend
        stdin_open: true
        environment:
           process.env.PUBLIC_URL: backend-service
        ports:
             - "3000:3000"
        depends_on:
             - backend-service
  backend:
      image: naveen5035/backend:v2
      container_name: backend-service
#      environment:
#         DB_NAME: loizenaidb
#         DB_USERNAME: postgres
#         DB_PASSWORD: 12345
#         DB_HOST: postgres
#          database: loizenaidb
#          username: postgres
#          password: 12345
#          host: postgres
      ports:
          - "8080:8080"
      depends_on:
            - postgres
  postgres:
          image: postgres:latest
          container_name: postgres
          ports:
              - "5432:5432"
          environment:
            POSTGRES_PASSWORD: 123
            POSTGRES_USER: postgres
            POSTGRES_DB: loizenaidb


