version: "3"
services:
  frontend:
    image: naveen5035/frontend:latest
    container_name: frontend
    stdin_open: true
    ports:
          - "3000:3000"
    environment:
        "proxy": "http://backend:8080"
  backend:
    image: naveen5035/backend:v1
    container_name: backend
    ports:
        - "8080:8080"
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
        - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: loizenaidb
