version: "3"
services:
  postgres:
            image: postgres:latest
            container_name: postgres
            ports:
                - "5432:5432"
            environment:
              POSTGRES_PASSWORD: 12345
              POSTGRES_USER: postgres
              POSTGRES_DB: loizenaidb
  backends:
        image: backend:v5
        container_name: backends
      environment:
         DATABASE: loizenaidb
         USERNAME: postgres
         PASSWORD: 12345
         HOST: postgres
        ports:
            - "8080:8080"
#  frontend:
#        image: frontend:v5
#        container_name: frontend
#        stdin_open: true
#        environment:
#           target: "http://backends:8080"
#        ports:
#             - "3000:3000"
