version: "3"
services:
  postgres:
          image: postgres:latest
          container_name: postgres
          ports:
              - "5432:5432"
          environment:
            POSTGRES_PASSWORD: 12345
            POSTGRES_USER: postgres
            POSTGRES_DB: loizenaidb
  backend:
    image: naveen5035/backend:v2
    container_name: backend
    environment:
      database: loizenaidb
      username: postgres
      password: 12345
      host: postgres
      dialect: postgres
    ports:
        - "8080:8080"
    depends_on:
          - postgres

  frontend:
          image: naveen5035/frontend:v2
          container_name: frontend
          stdin_open: true
          ports:
                - "3000:3000"
          depends_on:
                - backend