version: "3"
services:
  postgres:
      image: postgres:latest
      container_name: postgres
      ports:
          - "5432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123
        POSTGRES_DB: loizenaidb
  backend:
    image: naveen5035/backend:v1
    container_name: backend
    environment:
      POSTGRES_DATABASE: loizenaidb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_HOST: locahost
    ports:
        - "8080:8080"
  frontend:
      image: naveen5035/frontend:latest
      container_name: frontend
      stdin_open: true
      ports:
            - "3000:3000"