version: "3"
services:
  frontend:
        image: naveen5035/frontend:v2
        container_name: frontend
        stdin_open: true
        ports:
             - "3000:3000"
        depends_on:
             - backend
  backend:
      image: backend:v5
      container_name: backend
      environment:
#         DB_NAME: loizenaidb
#         DB_USERNAME: postgres
#         DB_PASSWORD: 12345
#         DB_HOST: postgres
          env.database: loizenaidb
          env.username: postgres
          env.password: 12345
          env.host: postgres
          env.dialect: postgres
      ports:
          - "8080:8080"
      depends_on:
            - postgres
  postgres:
          image: postgres:latest
          container_name: postgres
          ports:
              - "5432:5432"
          environment:
            POSTGRES_PASSWORD: 12345
            POSTGRES_USER: postgres
            POSTGRES_DB: loizenaidb


